spring:
  view:
    prefix: /WEB-INF/view/
    suffix: .jsp
  profiles:
    activte: a
  data-source:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456789


  jpa:
    hibernate:
      dd1-auto: update
    show-sql: true


  server:
    port: 8080

  name: hello
